### ISSUE TITLE
The bfrt_python cli of install/bin/bfswitchd

### ISSUE THREAD

**Issue by TingtingXuA** [p4lang/p4-dpdk-target#17]
We desire to run the bfrt_python CLI through install/bin/bfswitchd. However, the error occurs:
Traceback (most recent call last):
  File "/sde/install/lib/python3.8/bfrtcli.py", line 17, in <module>
    from traitlets.config import Config
  File "/sde/install/lib/python3.8/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/sde/install/lib/python3.8/site-packages/traitlets/config/application.py", line 18, in <module>
    from traitlets.config.configurable import Configurable, SingletonConfigurable
  File "/sde/install/lib/python3.8/site-packages/traitlets/config/configurable.py", line 11, in <module>
    from .loader import Config, LazyConfigValue, DeferredConfig, _is_section_key
  File "/sde/install/lib/python3.8/site-packages/traitlets/config/loader.py", line 16, in <module>
    from ipython_genutils.path import filefind
  File "/sde/install/lib/python3.8/site-packages/ipython_genutils/path.py", line 13, in <module>
    import random
  File "/sde/install/lib/python3.8/random.py", line 40, in <module>
    from cgi import print_form
  File "/sde/install/lib/python3.8/cgi.py", line 39, in <module>
    from email.parser import FeedParser
  File "/sde/install/lib/python3.8/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/sde/install/lib/python3.8/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/sde/install/lib/python3.8/email/_policybase.py", line 7, in <module>
    from email import header
  File "/sde/install/lib/python3.8/email/header.py", line 14, in <module>
    import binascii
ModuleNotFoundError: No module named 'binascii'
Failed to load bfrtcli python library
bfrt_cli_cmd:201 could not initialize bf_rt for the cli. err: 1

We print the sys.path by hacking the bfrtcli.py and shows that: 
bfshell> bfrt_python
['/sde/install/lib/python38.zip', '/sde/install/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/sde/install/lib/python3.8/site-packages'] 

We use the interactive interface of python3.8 and import the module named 'binascii'. It successes.  At the interactive interface, the sys.path is shown as followed:
>>> sys.path
['', '/sde/install/lib/python38.zip', '/sde/install/lib/python3.8', '/sde/install/lib/python3.8/lib-dynload', '/sde/install/lib/python3.8/site-packages']

**Comment by TingtingXuA** [comment]
The environment is wrong. I used a clear environment and solved it.
